### ISSUE TITLE
browser_agents.txt not found

### ISSUE THREAD

**Issue by michaelbukachi** [anthonyhseb/googlesearch#66]
* google-search version: 1.1.0
* Python version: 3.9
* Operating System: Ubuntu

### Description

When I try to run the snippet in the example, I get the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/Projects/PycharmProjects/webcrawler/venv/lib/python3.8/site-packages/googlesearch/browser_agents.txt'

```

### What I Did

```
gs = GoogleSearch()
results = gs.search(term, 20)
for result in results:
    print("Title: " + result.title)
    print("Content: " + result.getText())
    print()
```

The issue is in `MANIFEST.in`. By default, when building python packages, non .py files are not included.  See the image below:
![screenshot_20210308153728](https://user-images.githubusercontent.com/10145850/110322867-d2dfea80-8024-11eb-85d9-8f1a1062625f.png)

Adding `include googlesearch/browser_agents.txt` to MANIFEST.in should resolve the issue.

**Comment by AlexCaranha** [comment]
I copied manually the file "browser_agents.txt" to the path ... venv/lib/python3.8/site-packages/googlesearch/
It worked.

**Comment by michaelbukachi** [comment]
> I copied manually the file "browser_agents.txt" to the path ... venv/lib/python3.8/site-packages/googlesearch/
> It worked.

The intent of the PR is to avoid copying/changing stuff :sweat_smile:  I hope it gets merged.
