### ISSUE TITLE
hi.googlesearch by default returned section all of google engine. yes? how I get results of googlenews section??thanks

### ISSUE THREAD

**Issue by fazialnjd** [anthonyhseb/googlesearch#97]

**Comment by anthonyhseb** [comment]
Hello, the library only supports the main "Web" section only.  I personally do not intend to add support for the other sections but pull requests are welcome.

Have you considered using news-specific APIs such as this one: https://newsapi.org/s/google-news-api

I will close the ticket for the time being as this is not one of the intended features of the library.

**Comment by fazialnjd** [comment]
Thanks for your suggestion, but google-news-api allows this with a limit of 1000 requests per day. I am looking for unlimited access. 
I have another question, is it possible to receive the number of results of each "web" page separately, such as json format??

**Comment by spookyahell** [comment]
> I have another question, is it possible to receive the number of results of each "web" page separately, such as json format??

Where? In this project or with the newsapi.org thing? (Because that would be off-topic)
